expense-track-assignment-master/config/routes.rb
ExpenceTrackingApp::Application.routes.draw do

  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :users, only: [:index] do
    collection do
      get :get_registered_users
    end
  end

  resources :groups, only: [:new, :create] do
    member do
      get :details
    end
  end

  resources :expenses, only: [:new, :create]

end

expense-track-assignment-master/app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :group
  attr_accessible :amount, :description, :paid_by, :group_id
  validates :amount, presence: true

  ## If user has contributed in a group then calculating amount which will be
  ## shared by all group members.
  def self.calculate_share_amt(user, grp)
    paid_by_user = grp.expenses.where(paid_by: user.id).first
    return 0 unless paid_by_user.present?
    expense = paid_by_user.amount
    expense.to_f / grp.users.count.to_i
  end

  ## Calcualting owe/owed amount for a member of a group.
  def self.fetch_contri(user, share_amt, grp)
    contributor = grp.expenses.where(paid_by: user.id).first
    if contributor.present?
      user_expense = contributor.amount.to_f / grp.users.count.to_i
      user_expense.to_f - share_amt.to_f
    else
      share_amt * -1
    end
  end
end

expense-track-assignment-master/app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :group_members
  has_many :users, through: :group_members
  has_many :expenses

  validates :name, presence: true

  def self.create_group(params, owner, emails)
    grp = Group.new(name: params[:name], description: params[:description])
    if grp.save
      grp.group_members.create(user_id: owner.id, is_owner: true)
      emails.each do |email|
        logger.info"____email______#{email.inspect}"
        user = User.find_by_email(email)
        grp.group_members.create(user_id: user.id)
      end
    end
    grp
  end
end

expense-track-assignment-master/app/models/group_member.rb
class GroupMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  attr_accessible :group_id, :is_owner, :user_id
end

expense-track-assignment-master/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation,
                  :remember_me, :confirmed_at, :confirmation_token,
                  :authentication_token, :confirmation_sent_at,
                  :reset_password_token, :reset_password_sent_at
  has_many :group_members 
  has_many :groups, through: :group_members
  validates :name, presence: true

  def self.fetch_paid_by_user(user_id)
    User.find(user_id).name
  end 

  def self.validate_email(emails, user)
    if emails.empty? 
      msg = "Email can't be blank." 
    else
      emails.each do |email|
        if !User.find_by_email(email).present?
          msg = "#{email} is not registered."  
        elsif email.eql? user.email 
         msg = "Group owner is the default member!"
        end 
      end  
    end 
    msg  
  end  
end

expense-track-assignment-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

  def after_sign_in_path_for(resource)
    users_path
  end

  # protected
  # def authenticate_user!
  #   if user_signed_in?
  #     super
  #   else
  #     redirect_to '/users/sign_in'
  #     ## if you want render 404 page
  #     ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
  #   end
  # end
end

expense-track-assignment-master/app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  def create
    grp = Group.find(params[:group_id])
    @expense = grp.expenses.new(amount: params[:amount],
                                description: params[:description],
                                paid_by: current_user.id)
    if @expense.save
    	redirect_to users_path
    else
    	@err_msg = @expense.errors.full_messages[0]
    	render :action => 'new'
    end 	
  end
end

expense-track-assignment-master/app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
  end

  def create
    emails = params[:email][0].split(',').map(&:strip)
    emails.uniq!
    emails.pop
    @err_msg  = User.validate_email(emails, current_user)
    render :action => 'new' and return if @err_msg.present?
    group = Group.create_group(params, current_user, emails)
    if group.errors.full_messages.present?
      @err_msg = group.errors.full_messages[0]
      render :action => 'new'
    else
      redirect_to users_path
    end

  end

  ## Show details of each group.
  def details
    @grp = Group.find(params[:id])
    @expenses = @grp.expenses
    @members = @grp.users
  end
end

expense-track-assignment-master/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def get_registered_users
    @users = User.all
    render :json => { :users => @users.map{|user| user.email}}
  end
end

expense-track-assignment-master/app/helpers/application_helper.rb
module ApplicationHelper

  def fetch_contributors(members, user)
    members.reject { |member| member.id == user.id }
  end
end

expense-track-assignment-master/app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:error, :info, :success, :warning] unless const_defined?(:ALERT_TYPES)
  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g.
      # for devise messages set to nothing in a locale file.
      next if message.blank?
      type = :success if type == :notice
      type = :error if type == :alert
      next unless ALERT_TYPES.include?(type)
      Array(message).each do |msg|
        text = content_tag(:div, content_tag(:button, raw('&times;'),
        class: 'close',
        'data-dismiss' => 'alert'
        ) + msg.html_safe, class: "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

expense-track-assignment-master/app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?
    messages = resource.errors
               .full_messages
               .map { |msg| content_tag :div, msg, class: 'errorMsg' }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
end

expense-track-assignment-master/app/helpers/expenses_helper.rb
module ExpensesHelper
end

expense-track-assignment-master/app/helpers/groups_helper.rb
module GroupsHelper
end

expense-track-assignment-master/app/helpers/users_helper.rb
module UsersHelper
end

expense-track-assignment-master/app/views/expenses/create.js.erb
<%if @expense.errors.full_messages.present? %>
  $('#billerrormsg').replaceWith("<p id='errormsg'> <%= @expense.errors.full_messages[0] %> </p>");
<% else %>
  $('#addBill').modal('hide');
  $('.modal-backdrop').remove();
<% end %>

expense-track-assignment-master/app/views/expenses/new.html.erb
<h3>Add Bill</h3>
<%= form_tag('/expenses', class: 'form-horizontal') do %>
<p>With you and</p>
<div class="form-group">
<div class="col-sm-10">
<%= select_tag "group_id", options_from_collection_for_select(current_user.groups, "id", "name"), { class: "form-control" } %>
</div>
</div>
<div class="form-group">
<div class="col-sm-10">
<%= text_area_tag :description, nil, cols: '18', tabindex: '1', placeholder: 'Description', class: "form-control" %>
</div>
</div>
<div class="form-group">
<div class="col-sm-10">
<%= text_field_tag :amount, nil, tabindex: '1', placeholder: 'Amount', class: "form-control" %>
</div>
</div>
<p id='billerrormsg'></p>
<div class="modal-footer">
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
<%= submit_tag 'Add', class: 'btn btn-primary' %>
</div>
<% end %>

expense-track-assignment-master/app/views/groups/_group_list.html.erb
<ul class="grpList">
  <% current_user.groups.each do |grp| %>
    <li><%= link_to grp.name, details_group_path(grp.id) %></li>
  <% end %>
</ul>

expense-track-assignment-master/app/views/groups/details.html.erb
<h4><%= @grp.name%></h4>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Date</th>
      <th>Item</th>
      <th>Amount</th>
      <th>Paid by</th>
    </tr>
  </thead>
  <tbody>
    <% @expenses.each do |expense| %>
    <tr>
      <td><%= expense.created_at.strftime('%m/%d/%Y')%></td>
      <td><%= expense.description%></td>
      <td><%= expense.amount%></td>
      <td><%= User.fetch_paid_by_user(expense.paid_by)%></td>
    </tr>
    <% end %>
  </tbody>
</table>
  <h5><%= current_user.name %> report:</h5>
  <% share_amt = Expense.calculate_share_amt(current_user, @grp)%>
  <% contributors = fetch_contributors(@members, current_user) %>
  <table class="table table-bordered">
  <thead>
    <tr>
      <th>Member</th>
      <% contributors.each do |cont| %>
        <th><%= cont.name %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= current_user.name %></td>
    <% contributors.each do |cont| %>
      <% amt = Expense.fetch_contri(cont, share_amt, @grp)%>
      <td><%=  amt > 0 ? 'Pay : ' : 'Get : '%><%= amt.abs %></td>
    <% end %>
    </tr>
  </tbody>
</table>

expense-track-assignment-master/app/views/groups/new.html.erb
<h3>Create Group</h3>
<%= form_tag('/groups', class: 'form-horizontal') do %>
  <div class="form-group">
    <div class="col-sm-10">
      <%= text_field_tag :name, nil, tabindex: '1', placeholder: 'Name', autofocus: true, class: "form-control"%>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= text_area_tag :description, nil, cols: '18', tabindex: '1', placeholder: 'Description',
      class: "form-control" %>
    </div>
  </div>
  <p>Add member</p>
  <div class="form-group">
    <div class="col-sm-10">
      <input type="text" id='email' name="email[]" tabindex="1" placeholder="Email Address" class="form-control"/>
    </div>
  </div>
  <p id='errormsg'><%= @err_msg.present? ? @err_msg : ''%></p>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <%= submit_tag 'Add', class: "btn btn-primary" %>
</div>
<% end %>

expense-track-assignment-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExpenceTrackingApp</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <!-- <link href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="Stylesheet"></link> -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js" ></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class='nav-v'>
      <div class="navbar-header">
        <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href='javascript:void(0)' class="navbar-brand">Expense Tracking</a>
      </div>
      <% if user_signed_in? %>
        <div class="navbar-collapse collapse navbar-right" id="navbar">
          <%= link_to 'LogOut', '/users/sign_out', 'data-method' => 'delete', class: "btn btn-success" %>
        </div>
      <% end %>
      </div>
    </nav>
    <% if user_signed_in? %>
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href='javascript:void(0)'>Groups<span class="sr-only">(current)</span></a></li>
              <%= render 'groups/group_list' %>
          </ul>
        </div>
        <div class="col-sm-9 col-md-10">
          <h3 class="page-header header"><%= link_to 'Welcome ' + current_user.name, users_path %></h3>
          <%=link_to 'Create Group', new_group_path, class: "btn btn-info btn-sm"%>
          <%=link_to 'Add Bill', new_expense_path, class: "btn btn-info btn-sm" %>
          <%= yield %>

          <!-- Popup for create group-->
          <div id="addGroup" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" style='background-color:"#fff"'>
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title" id="myModalLabel">Create Group</h4>
                </div>

              </div>
            </div>
          </div>

          <!-- Popup for create bill-->
          <div id="addBill" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" style='background-color:"#fff"'>
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Add Bill</h4>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
  </div>
</body>
</html>